# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fda8b25e470739ddf23aa4326d402961201d9345de54f166ae1efc7f78ea8573991ae2a462d62b185784ffe92dc812d7f07aa748de0081d7ff6228bbf1943b1

test:
  secret_key_base: d9c48c033f06860f738c817c57594d2b87344cb3f5755b255339a9dba746e970c8b655f0a07d7631251161b652cd7f4d5de520247d68ddf457d50391d05f3a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
